### ISSUE TITLE
Code is locked in setup if sensor is not present at boot time

### ISSUE THREAD

**Issue by ciberp** [malokhvii-eduard/arduino-bme280#2]
Hi!

I just used this library and if sensor is not connected at boot time, then program stays in setup in an infinite loop. 

```
void setup() {
  Serial.begin(9600);
  Wire.begin(D2, D1);

  Serial.println();

  sensor.begin(Bme280TwoWireAddress::Primary);  <---- here
  sensor.setSettings(Bme280Settings::indoor());
}
```
Bme280.cpp:
```
  while (isImUpdate()) {   <--- because of this
    delay(20);
  }
```

I fixed it by changing with:
```
 isImUpdate();
```

Is this code lock done intentionally or is it just a mistake?

Thank you, regards,
Peter

**Comment by malokhvii-eduard** [comment]
@ciberp Hi! Thanks for the issue. I will think about how to solve the issue more elegantly. What do you suggest? Maybe, we can return an error code from the `begin` method?

**Comment by ciberp** [comment]
Hi!

Error code to indicate the problem with sensor would be a good approach.

**Comment by malokhvii-eduard** [comment]
@ciberp Great news! Now, we can check the status of the `begin`, also we can change timeout via `ARDUINO_BME280_TIMEOUT` macro, by default it equals 10 seconds.
