### ISSUE TITLE
Set a specific (setting) parameter, starting from a factory preset 

### ISSUE THREAD

**Issue by FerGT50** [malokhvii-eduard/arduino-bme280#4]
Hello, thanks for the library.

Let's say I want to set the BME280 in Forced mode, while all other settings I would take from the "indoor" preset.
How would I do that, is there an example? Only found examples about enabling one of the presets (Settings.ino) as is.
Thanks

**Comment by malokhvii-eduard** [comment]
Hello,

I'm glad to hear you're using the library! To set the BME280 in the _forced mode_ while using the _indoor_ preset for other settings, you can make use of the `setSettings` method. Here's an example of how you can achieve this:

**Comment by malokhvii-eduard** [comment]
@FerGT50 Hello,

I'm glad to hear you're using the library! To set the BME280 in forced mode while using the indoor preset for other settings, you can make use of the `setSettings` method. Here's an example of how you can achieve this:

```cpp
#include <Arduino.h>
#include <Bme280.h>

Bme280TwoWire sensor;

void setup() {
  Serial.begin(9600);
  Wire.begin(D2, D1);

  Serial.println();

  sensor.begin(Bme280TwoWireAddress::Primary);

  auto settings = Bme280Settings::indoor();  // Use indoor preset
  settings.mode = Bme280Mode::Forced;  // Modify mode
  sensor.setSettings(settings);  // Set settings
}

void loop() {}
```

**Comment by FerGT50** [comment]
Thanks!

**Comment by FerGT50** [comment]
(solved)

**Comment by malokhvii-eduard** [comment]
@FerGT50 You're welcome. Also you can give a star to the project.
